package rzd.asoup3.proto.rule.message.Pms28672867

rule 'format-SF0-1000' dialect "mvel"
when
    eval(true)
then
    System.out.println("format-SF0-1000");
end

rule 'format-IF1-1001' dialect "mvel"
when
    eval(true)
then
    System.out.println("format-IF1-1001");
end

rule 'default-STANF-0000' dialect "mvel"
when
    eval(true)
then
    System.out.println("default-STANF-0000");
end

rule 'calc-DATSO' dialect "mvel"
when
    eval(true)
then
    System.out.println("calc-DATSO");
end

rule 'extra' dialect "mvel"
when
    eval(true)
then
    System.out.println("extra");
end
